### ISSUE TITLE
NPE when using pre-built Mac binary

### ISSUE THREAD

**Issue by wimdeblauwe** [edvin/fxldemo#2]
I am interested in an auto-updater and I tried the small jar, which works perfectly. I also tried the native mac installer, but this one gives the following NPE when I start the application:

```
java.lang.NullPointerException
    at no.tornado.FxlDemo.start(FxlDemo.java:33)
    at fxlauncher.Launcher.lambda$launchAppFromManifest$2(Launcher.java:101)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```

**Comment by edvin** [comment]
Thanks for reporting this. It is a result of me playing with the new Gradle plugin, and I forgot some cleanup. I'll fix it ASAP.

**Comment by edvin** [comment]
There, now it should be working. Can you confirm that it's working for you as well?

**Comment by wimdeblauwe** [comment]
I can confirm it works now.

**Comment by edvin** [comment]
Thanks for getting back to me. Great!
