### ISSUE TITLE
Following instructions is not provided a running app

### ISSUE THREAD

**Issue by ouaibsky** [edvin/fxldemo#3]
Hi

* I checkout this project under windows
* run 
> create-native-installer.bat
* start: 
> java -jar target\app\fxlauncher.jar

I got error with dialog saying **"java.lang.ClassNotFoundException: no.tornado.FxlDemo"**

Do I miss something ?

**Comment by edvin** [comment]
I just did the exact same thing and it worked without issues. Can you post the output you see in the shell?

**Comment by ouaibsky** [comment]
```
$JAVA_HOME/bin/java -jar target/installer/fxlauncher.jar
logging to C:\Users\user\AppData\Local\Temp\\fxlauncher.log
Mar 21, 2017 3:07:16 PM fxlauncher.AbstractLauncher syncManifest
WARNING: Unable to update manifest from http://fxldemo.tornado.no/app.xml
java.net.UnknownHostException: fxldemo.tornado.no
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at fxlauncher.FXManifest.load(FXManifest.java:169)
        at fxlauncher.AbstractLauncher.syncManifest(AbstractLauncher.java:214)
        at fxlauncher.AbstractLauncher.updateManifest(AbstractLauncher.java:92)
        at fxlauncher.Launcher.lambda$start$0(Launcher.java:121)
        at java.lang.Thread.run(Thread.java:745)

Mar 21, 2017 3:07:16 PM fxlauncher.AbstractLauncher syncFiles
INFO: Using cache dir C:\Users\clalleme\AppData\Local\FxlDemo
Mar 21, 2017 3:07:16 PM fxlauncher.Launcher lambda$start$0
WARNING: Error during File Synchronization phase
java.net.UnknownHostException: fxldemo.tornado.no
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at fxlauncher.AbstractLauncher.syncFiles(AbstractLauncher.java:133)
        at fxlauncher.Launcher.lambda$start$0(Launcher.java:123)
        at java.lang.Thread.run(Thread.java:745)

Mar 21, 2017 3:07:16 PM fxlauncher.Launcher$1 reportError
WARNING: Error during Create Application phase
java.lang.ClassNotFoundException: no.tornado.FxlDemo
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at fxlauncher.AbstractLauncher.createApplicationEnvironment(AbstractLauncher.java:161)
        at fxlauncher.Launcher.lambda$start$0(Launcher.java:133)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by edvin** [comment]
You cannot deploy towards fxldemo.tornado.no, since you don't have access to it, and there wouldn't be any point - you want to deploy YOUR app :)

Remember to update the host, username, password and application class in the deployment descriptor before attempting to deploy your application.

**Comment by ouaibsky** [comment]
I expected that at least if the URL is no available you can start local version ?

**Comment by edvin** [comment]
That's correct, but it needs to download the application files once. The stack trace above suggests that your machine is unable to lookup the host name `fxldemo.tornado.no`, so it wasn't able to download the initial files needed for the first run.

Can you confirm that you can reach `http://fxldemo.tornado.no/app.xml` with your browser and that you're not behind a network that requires proxy configuration?

**Comment by ouaibsky** [comment]
I confirm I'm not able to contact **http://fxldemo.tornado.no/app.xml** because I'm behind a proxy that block it.

I'll do a test by finding a webserver where I can put files.

Should it be nice to be able to test locally before deploying on a web server ?
inside app, you get all materials (fxlauncher, app.xml ad libs).

Thx
Christophe

**Comment by edvin** [comment]
I think it's now possible to test via a `file://` url - isn't that right @ronsmits?

**Comment by ronsmits** [comment]
Yes but it seems the fxlauncher in the fxldemo.tornado.no is a bit old. With the new one you should be able to download everything and then run `java -jar fxlauncher.jar --app=app.xml --cache-dir=.` if you downloaded all the files to the same directory.

If @ouaibsky cannot access the website, he will have to do that because fxlauncher will also not be able to access it.

**Comment by edvin** [comment]
OK, thanks! Will push 1.0.15 right away.

**Comment by edvin** [comment]
I'll close the issue since it's not really a problem with FXLauncher :)

**Comment by ouaibsky** [comment]
Thx for the information
I confirm it's working fine when deploying app.xml into a webserver.

Christophe.
